apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: vmq-operator
    app.kubernetes.io/version: latest
  name: vmq-operator
  namespace: messaging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vmq-operator
subjects:
- kind: ServiceAccount
  name: vmq-operator
  namespace: messaging
